name: "Terraform Module Build"

on:
  pull_request:
    types: 
      - closed

permissions:
  id-token: write
  contents: write

jobs:
  build:
    if: github.event.pull_request.merged == true 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: main
        fetch-depth: 0
    
    - name: Bump version and push tag
      id: tag
      uses: anothrNick/github-tag-action@1.64.0 
      env:
        DEFAULT_BRANCH: main
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        WITH_V: true
    
    - name: Generate release    
      uses: marvinpinto/action-automatic-releases@latest
      with:
        automatic_release_tag: ${{ steps.tag.outputs.tag }}
        repo_token: ${{ secrets.GITHUB_TOKEN }}  
        prerelease: false
        draft: false
